version: '3.8'
services:
  app:
    container_name: app
    build: .
    tty: true
    command: yarn run-p start:dev db:studio
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/app
    depends_on:
      - mysql
    env_file:
      - ./prisma/.env

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./prisma/data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9090:9000
      - 33023:33023
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    entrypoint: sh
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      /opt/bin/minio server /data --console-address :33023;
      "
    volumes:
      - ./minio:/data
