# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.0
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn typecheck
      - name: setup containers
        run: |
          yarn up
          docker exec app -T yarn db:apply
          docker exec app -T yarn db:seed
      - run: docker exec -T app yarn test
      - run: docker exec -T app yarn test:e2e
